language: c
sudo: required
install:
  - pip install --user cpp-coveralls
before_script:
  - git clone http://git.openwrt.org/project/ubox.git ubox
  - pushd ubox && mkdir build && cd build && cmake .. && make && sudo make install && popd
  - git clone http://git.openwrt.org/project/uci.git uci
  - pushd uci && mkdir build && cd build && cmake .. && make && sudo make install && popd
  - git clone https://github.com/mkschreder/libutype.git libutype
  - pushd libutype && autoreconf -if && ./configure --prefix=/usr/ && make && sudo make install && popd
  - git clone https://github.com/mkschreder/libblobpack.git libblobpack
  - pushd libblobpack && autoreconf -if && ./configure --prefix=/usr/ && make && sudo make install && popd
script: autoreconf -if && ./configure --enable-code-coverage && make && make check
after_success:
  - coveralls
addons:
  apt:
    packages:
    - lcov
    - lua5.1
