language: c
sudo: required
install:
  - pip install --user cpp-coveralls
before_script:
  - git clone https://github.com/warmcat/libwebsockets.git libwebsockets
  - pushd libwebsockets &&  git checkout v2.0.2 && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make && sudo make install && popd 
  - git clone https://github.com/mkschreder/libutype.git libutype
  - pushd libutype && autoreconf -if && ./configure --prefix=/usr/ && make && sudo make install && popd
  - git clone https://github.com/mkschreder/libusys.git libusys
  - pushd libusys && autoreconf -if && ./configure --prefix=/usr/ && make && sudo make install && popd
  - git clone https://github.com/mkschreder/libblobpack.git libblobpack
  - pushd libblobpack && autoreconf -if && ./configure --prefix=/usr/ && make && sudo make install && popd
script: autoreconf -if && ./configure --enable-code-coverage --enable-valgrind CFLAGS="-g -O0" && make && make check && make -C test check-valgrind 
after_success:
  - coveralls
addons:
  apt:
    packages:
    - lcov
    - lua5.1
    - lua5.1-dev
