language: c
sudo: required
install:
  - pip install --user cpp-coveralls
before_script:
  - git clone https://github.com/mkschreder/libutype.git libutype
  - pushd libutype && ./configure --prefix=/usr/ && make && sudo make install && popd
  - wget https://github.com/mkschreder/libblobpack/archive/2.16.08.tar.gz -O /tmp/blobpack.tar.gz
  - tar -xzvf /tmp/blobpack.tar.gz 
  - pushd libblobpack-2.16.08 && ./configure --prefix=/usr/ && make && sudo make install && popd
script: autoreconf -if && ./configure --enable-code-coverage && make && make check
after_success:
  - coveralls
addons:
  apt:
    packages:
    - lcov
    - lua5.1
